#!/usr/bin/env python3
"""Seed the k-stack knowledge graph by driving the binary over stdio JSON-RPC.

Reads knowledge/graph/seed.jsonl, stores each node via `ket_store`, resolves
parent ids to CIDs, and writes knowledge/graph/cids.lock (committed alongside
the manifest so divergence is detectable by diff).

Usage:  KET_HOME=.ket python3 knowledge/scripts/seed.py
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "knowledge" / "graph" / "seed.jsonl"
LOCKFILE = ROOT / "knowledge" / "graph" / "cids.lock"
BINARY = ROOT / "k-stack" / "target" / "release" / "k-stack"

# Domain kind -> k-stack NodeKind
KIND_MAP = {
    "schema": "cdom",
    "decision": "reasoning",
    "invariant": "reasoning",
    "component": "code",
    "event": "memory",
}


def main() -> int:
    if not BINARY.exists():
        print(f"error: k-stack binary missing at {BINARY}", file=sys.stderr)
        print("hint: (cd k-stack && cargo build --release)", file=sys.stderr)
        return 1

    env = os.environ.copy()
    env.setdefault("KET_HOME", str(ROOT / ".ket"))

    proc = subprocess.Popen(
        [str(BINARY)],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
        text=True,
        bufsize=1,
    )

    req_id = 0

    def call(method: str, params: dict) -> dict:
        nonlocal req_id
        req_id += 1
        msg = {"jsonrpc": "2.0", "id": req_id, "method": method, "params": params}
        assert proc.stdin and proc.stdout
        proc.stdin.write(json.dumps(msg) + "\n")
        proc.stdin.flush()
        line = proc.stdout.readline()
        if not line:
            err = proc.stderr.read() if proc.stderr else ""
            raise RuntimeError(f"no response from k-stack: {err}")
        resp = json.loads(line)
        if "error" in resp and resp["error"]:
            raise RuntimeError(f"{method} failed: {resp['error']}")
        return resp.get("result", {})

    # MCP handshake
    call("initialize", {"protocolVersion": "2024-11-05", "capabilities": {}})

    cid_by_id: dict[str, str] = {}
    entries: list[dict] = []

    with MANIFEST.open() as f:
        for raw in f:
            raw = raw.strip()
            if not raw:
                continue
            rec = json.loads(raw)
            domain_kind = rec["kind"]
            node_kind = KIND_MAP[domain_kind]
            ident = rec.get("id") or rec.get("ref")

            if domain_kind in ("schema", "decision"):
                content = (ROOT / "knowledge" / rec["ref"]).read_text()
            elif domain_kind == "invariant":
                content = json.dumps(
                    {
                        "id": rec["id"],
                        "statement": rec["statement"],
                        "penalty": rec.get("penalty"),
                    },
                    sort_keys=True,
                )
            else:
                content = json.dumps(rec, sort_keys=True)

            parents_cids = [cid_by_id[p] for p in rec.get("parents", [])]

            result = call(
                "tools/call",
                {
                    "name": "ket_store",
                    "arguments": {
                        "content": content,
                        "kind": node_kind,
                        "parents": parents_cids,
                        "agent": "seed.py",
                    },
                },
            )

            # MCP wraps tool results in content[] blocks
            if "content" in result and isinstance(result["content"], list):
                inner = json.loads(result["content"][0]["text"])
            else:
                inner = result

            node_cid = inner["node_cid"]
            content_cid = inner["content_cid"]
            cid_by_id[ident] = node_cid
            entries.append(
                {
                    "id": ident,
                    "domain_kind": domain_kind,
                    "node_kind": node_kind,
                    "node_cid": node_cid,
                    "content_cid": content_cid,
                    "parents": rec.get("parents", []),
                }
            )
            print(f"{domain_kind:10}  {ident:36}  {node_cid}")

    proc.stdin.close()
    proc.wait(timeout=5)

    LOCKFILE.write_text(
        "# AUTOGENERATED by knowledge/scripts/seed.py — do not edit.\n"
        "# If two peers' cids.lock differ, the content at the differing CID differs.\n"
        + "\n".join(json.dumps(e, sort_keys=True) for e in entries)
        + "\n"
    )
    print(f"\nwrote {LOCKFILE.relative_to(ROOT)} ({len(entries)} nodes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
